## Using NumPy

Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [12]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [13]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [15]:
np.random.rand(2)

array([0.43600409, 0.90879359])

In [16]:
np.random.rand(5,5)

array([[0.15740914, 0.53329311, 0.66525601, 0.19029638, 0.80001939],
       [0.67511247, 0.69909811, 0.66400411, 0.3112203 , 0.06932347],
       [0.27404777, 0.25092112, 0.78079782, 0.6255849 , 0.57154794],
       [0.32104205, 0.09740196, 0.14914883, 0.1158768 , 0.77571459],
       [0.45073903, 0.88749707, 0.83279461, 0.55174705, 0.39925866]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [17]:
np.random.randn(2)

array([-1.93336695, -0.52713117])

In [18]:
np.random.randn(5,5)

array([[ 1.02582689, -0.47618556, -0.99294877, -0.43444994,  0.21505526],
       [-0.90606508,  0.58250886, -0.62132832, -0.70441437,  0.88144543],
       [ 0.15657463,  0.16023491, -0.05620424,  1.43484528,  0.06684438],
       [-0.67117951,  0.4705206 ,  3.02684791,  0.87548311, -0.21293639],
       [ 0.07428574, -0.07592848,  2.13794369,  0.38610559,  1.73878439]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [19]:
np.random.randint(1,100)

37

In [20]:
np.random.randint(1,100,10)

array([41, 78, 46,  9, 53, 67, 92, 90, 15, 58])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [21]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
ranarr

array([ 3,  0, 10, 14, 35, 42,  7, 27, 43, 28])

## Reshape
Returns an array containing the same data with a new shape.

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [25]:
ranarr

array([ 3,  0, 10, 14, 35, 42,  7, 27, 43, 28])

In [26]:
ranarr.max()

43

In [27]:
ranarr.argmax()

8

In [28]:
ranarr.min()

0

In [29]:
ranarr.argmin()

1

## Shape

Shape is an attribute that arrays have (not a method):

In [30]:
# Vector
arr.shape

(25,)

In [31]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [32]:
arr.reshape(1,25).shape

(1, 25)

In [33]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [34]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [35]:
arr.dtype

dtype('int64')